config/routes.rb
Quizzer::Application.routes.draw do
  resources :terms do
  	collection do
			get 'quiz'
		end
  end

  root to: 'terms#index'

end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @terms }
    end
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
    @term = Term.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/new
  # GET /terms/new.json
  def new
    @term = Term.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/1/edit
  def edit
    @term = Term.find(params[:id])
  end

  # GET /terms/1/quiz
  def quiz

		def getForm(term, form)
			return case form
				when "english"
					term.english
				when "romanji"
					term.romanji
				when "kana"
					term.kana
				when "kanji"
					term.kanji
			end
		end
		
		@term = Term.find(:first, :order=>'random()')

		from_form = params[:from] || "kana"
		to_form   = params[:to  ] || "english"

		@prompt = getForm(@term, from_form)
		@answer = getForm(@term, to_form)

		if (params[:from] == "english" and params[:to] == "kanji")
			@second_answer = getForm(@term, "kana")
		end

    respond_to do |format|
      format.html # quiz.html.erb
    end
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(params[:term])

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render json: @term, status: :created, location: @term }
      else
        format.html { render action: "new" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /terms/1
  # PUT /terms/1.json
  def update
    @term = Term.find(params[:id])

    respond_to do |format|
      if @term.update_attributes(params[:term])
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term = Term.find(params[:id])
    @term.destroy

    respond_to do |format|
      format.html { redirect_to terms_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizzer</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/terms/_form.html.erb
<%= form_for(@term) do |f| %>
  <% if @term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
      <% @term.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :english, :id => "english_field" %><br />
    <%= f.text_field :english %>
  </div>
  <div class="field">
    <%= f.label :romanji %><br />
    <%= f.text_field :romanji %>
  </div>
  <div class="field">
    <%= f.label :kana %><br />
    <%= f.text_field :kana %>
  </div>
  <div class="field">
    <%= f.label :kanji %><br />
    <%= f.text_field :kanji %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

	<script type="text/javascript">
		document.getElementById("english_field").focus();
	</script>

<% end %>

app/views/terms/edit.html.erb
<h1>Editing term</h1>

<%= render 'form' %>

<%= link_to 'Show', @term %> |
<%= link_to 'Back', terms_path %>

app/views/terms/index.html.erb
<h1>Listing terms</h1>

<table>
  <tr>
    <th>English</th>
    <th>Romanji</th>
    <th>Kana</th>
    <th>Kanji</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @terms.each do |term| %>
  <tr>
    <td><%= term.english %></td>
    <td><%= term.romanji %></td>
    <td><%= term.kana %></td>
    <td><%= term.kanji %></td>
    <td><%= link_to 'Show', term %></td>
    <td><%= link_to 'Edit', edit_term_path(term) %></td>
    <td><%= link_to 'Destroy', term, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Term', new_term_path %>
<%= link_to 'Quiz', quiz_terms_path %>

app/views/terms/new.html.erb
<h1>New term</h1>

<%= render 'form' %>

<%= link_to 'Back', terms_path %>

app/views/terms/quiz.html.erb
<div style="background: #def; width: 100%; padding-top: 150px; text-align: center; vertical-align: center;" onclick="showAnswer()">
	<font size="30"><%= @prompt %></font>
	<br><br><br>
	<div id="answer" style="display:none; ">
		<font style="font-size:30pt;"><%= @answer %></font><br><br>
		<font style="font-size:16pt;"><%= @second_answer %></font>
	</div>
	<br><br><br><br>
	<br>

</div>

<%= link_to 'Edit this term', edit_term_path(@term) %> |
<%= link_to 'Back to listing', terms_path %> |
<%= link_to 'New term', new_term_path, :id => 'new_term_link' %>
<br>
<br>

<%= link_to 'かな to English' , quiz_terms_path + '?from=kana&to=english' %><br>
<%= link_to 'English to かな' , quiz_terms_path + '?from=english&to=kana' %><br>
<%= link_to '漢字 to English', quiz_terms_path + '?from=kanji&to=english' %><br>
<%= link_to 'English to 漢字', quiz_terms_path + '?from=english&to=kanji' %><br>
<%= link_to '漢字 to English', quiz_terms_path + '?from=kanji&to=english' %><br>
<%= link_to 'かな to 漢字'   , quiz_terms_path + '?from=kana&to=kanji' %><br>


<script type="text/javascript">
	document.getElementById("new_term_link").focus()
	state=0;
	function showAnswer() {
		if (state == 0) {
			//1st click: show the answer
			document.getElementById("answer").style.display = "block"
			state = state + 1
		} else {
			//2nd click: reload page for new word
			window.location = window.location
		}
	}
</script>

app/views/terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>English:</b>
  <%= @term.english %>
</p>

<p>
  <b>Romanji:</b>
  <%= @term.romanji %>
</p>

<p>
  <b>Kana:</b>
  <%= @term.kana %>
</p>

<p>
  <b>Kanji:</b>
  <%= @term.kanji %>
</p>


<%= link_to 'Edit', edit_term_path(@term) %> |
<%= link_to 'Back to listing', terms_path %> |
<%= link_to 'New term', new_term_path, :id => 'new_term_link' %>

<script type="text/javascript">
	document.getElementById("new_term_link").focus()
</script>